# Your workflow name.
name: Deploy

# Run workflow on every push to main branch.
on:
  push:
    branches:
      - main

# Your workflows jobs.
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      # Deploy to Render
      - name: Deploy to Render
        uses: render-actions/deploy@v1
        with:
          renderToken: ${{ secrets.RENDER_TOKEN }} # Set your Render token as a secret in your repository
          renderFile: render.yaml # Path to your Render configuration file (render.yaml)
